package com.kskb.se.http;

public class EmbeddedResources {
   private static final String FAVICON_B64_STR = """
        AAABAAEAFRQAAAEAIAAIBwAAFgAAACgAAAAVAAAAKAAAAAEAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP//
        /wD///8AAAAAAAAAAAAAAAAAAAAAAAAAAAD///8A////AP///wD///8AAG7pGBhRqf0WU7P/CljX/wpY
        1/8KWNf/DFjS/xhRqP8VWLfUCmbXkCIyWtD///8AAAAAAAAAAAAAAAAAAAAAAAAAAAD///8A////AP//
        /wD///8AAG7pLgBu6f8Aben/AFzo/wBb6P8AW+j/AFvo/wBu6f8hNWXIAG7pmB8+etX///8AAAAAAAAA
        AAAAAAAAAAAAAAAAAAD///8A////ACUlJQYkJCRuIyo+NAFt5/AAbun/AGvp/wBd6P8AW+j/AFvo/wBu
        6f8fQH7WAG7omh8+edb///8AAAAAAAAAAAAAAAAAAAAAAAAAAAD///8AJCYvTSA6btoLZNTPHkGCwQBu
        6UUBbuj1AG7p/wBi6P8AW+j/AF7o/wBu6f8fQH7VA2vjqh8+ecf///8AAAAAAAAAAAAAAAAAAAAAAAAA
        AAD///8AFFq84gVq3/UVWLfmFVi4+iQkJEgGad4jAm3m6QBp6f8AW+j/AGPo/wBu6f8eQoTABGvixiIu
        TqP///8AAAAAAAAAAAAAAAAAAAAAAAAAAAD///8ACGjb5A9gy/oDa+P/Amzl/xZVsv8eQoX1FFm52QBq
        6f8AX+j/AG3p/wBu6f8gO3OcBWrh2yQkJHv///8AAAAAAAAAAAAAAAAAAAAAAAAAAAD///8ABGvibwBu
        6f8Abun/AG7p/wBu6f8Abun/AW3o/wBt6f8Abun/AG7p/wRr4/8kKDZUCGfa4yQkJEX///8AAAAAAAAA
        AAAAAAAAAAAAAAAAAAD///8A////AAVq4MoAbun/AG7p/wBu6f8Abun/AG7p/wBu6f8Abun/AG7p/xFe
        xfkHaNxOFVi46CUlJQP///8AAAAAAAAAAAAAAAAAAAAAAAAAAAD///8A////AABu6R8Abun/D2HM1gFt
        5/sAbun/AG7p/wBu6f8Abun/AG7o/xpOoHgKZtfUHkOGgv///wD///8AAAAAAAAAAAAAAAAAAAAAAAAA
        AAD///8A////AP///wAFat/xC2XU/wlm2P8Abun/AG7p/wBu6f8Bbej/El3CmhJcwpkUWr3I////AP//
        /wD///8AAAAAAAAAAAAAAAAAAAAAAAAAAAD///8A////AP///wAHaNyWAmzl/wFt5/wAbun/AW3n/xBg
        ydgXVK6IElzByxFexp7///8A////AP///wD///8AAAAAAAAAAAAAAAAAAAAAAAAAAAD///8A////AP//
        /wAAbukNAW3n/g5hzfAAbun/A2vj/xFexawKZdZ6AG7pEf///wD///8A////AP///wD///8AAAAAAAAA
        AAAAAAAAAAAAAAAAAAD///8A////AP///wD///8ABWrh9xZXtVADbOT3FVe1tP///wD///8A////AP//
        /wD///8A////AP///wD///8AAAAAAAAAAAAAAAAAAAAAAAAAAAD///8A////AP///wD///8ACmbXMv//
        /wALZdVq////AP///wD///8A////AP///wD///8A////AP///wD///8AAAAAAAAAAAAAAAAAAAAAAAAA
        AAD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP//
        /wD///8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAD///gA8AH4APAB+ADAAfgAgAH4AIAB+ACAAfgAgAH4AMAB+ADAA/gA4Af4AOAP+ADgH/gA8P/4APX/
        +AD///gA///4AP//+AD///gA///4AA==
        """;
}
